# vim ft=yaml
# travis-ci.org definition for skfuzzy build, modified from scikit-image

# After changing this file, check it on:
#   http://lint.travis-ci.org/

language: python


python:
    - 3.8

env:
    - ENV="python=3.5 numpy"
    - ENV="python=3.6 numpy"
    - ENV="python=3.7 numpy"
    - ENV="python=3.8 numpy"

services:
    - xvfb

before_install:
    - sudo apt-get update
    - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh;
    - bash miniconda.sh -b -p $HOME/miniconda;
    - export PATH="$HOME/miniconda/bin:$PATH";
    - hash -r;
    - conda config --set always_yes yes;
    - conda update conda;
    - conda info -a;
    - travis_retry conda create -n test $ENV scipy pip pytest flake8 nose networkx matplotlib;
    - source activate test;
    - travis_retry conda install pillow;
    - travis_retry pip install coveralls

install:
    - tools/header.py "Dependency versions"
    - tools/build_versions.py
    - export PYTHONWARNINGS=all
    - python setup.py build_ext --inplace

script:
    # Run all tests with minimum dependencies
    - nosetests --exe -v skfuzzy

    # Run pep8 and flake tests
    - flake8 --exclude=test_* skfuzzy docs/examples

after_success:
    - coveralls
